name: treeo_delivery
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  
dependencies:
  cloud_firestore: ^4.13.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  firebase_auth: ^4.15.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  intl: ^0.19.0
  lottie: ^2.6.0
  page_animation_transition: ^1.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
    
  very_good_analysis: ^5.1.0
  
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - shorebird.yaml
    
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Regular.ttf
          weight: 600
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 700
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: fonts/Gilroy-Bold.ttf
          weight: 800
        - asset: fonts/Gilroy-Thin.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
